name: Master Build
on:
  push:
    branches:
      - 'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - name: Perform source code checkout
      uses: actions/checkout@v1
    - name: Turnstyle Action
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: Perform build
      run: |
        npm run build
    - name: Run test
      run: |
          npm run test:sample
    - name: Generate report
      run: |
          npm run test:report
    - name: Upload allure report
      uses: actions/upload-artifact@v1
      with:
        name: allure-report
        path: allure-report