name: Production Build
on:
  push:
    tags:
      - 'release-*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - name: Perform source code checkout
      uses: actions/checkout@v1
    - name: Turnstyle Action
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: npm install
      run: |
        npm install
    - name: Perform build
      run: |
        npm run build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete --debug
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME_PRD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
        AWS_REGION: ${{ secrets.AWS_REGION_PRD }}
        SOURCE_DIR: "dist"
    - name: Invalidate cloudfront cache
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID_PRD }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}